name: 'automation'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - ${VOLUMES_BASEDIR}/n8n:/home/node/.n8n
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
