name: "monitoring"

services:
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      HUB_URL: ${HUB_URL}
      TOKEN: ${TOKEN}
      KEY: ${KEY}
    healthcheck:
      test: ['CMD', '/agent', 'health']
      interval: 120s

volumes:
  beszel_agent_data:
  beszel_socket:
