name: 'llm'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_AUTH=False
    volumes:
      - ${VOLUMES_BASEDIR}/open_webui:/app/backend/data
    networks:
      - proxy_proxy-net

  langfuse-server:
    image: langfuse/langfuse:2
    container_name: langfuse-server
    restart: unless-stopped
    depends_on:
      langfuse-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${LANGFUSE_DB_USER}:${LANGFUSE_DB_PASSWORD}@langfuse-db:5432/${LANGFUSE_DB_NAME}
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${LANGFUSE_NEXTAUTH_URL}
      - SALT=${LANGFUSE_SALT}
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY} # generate via `openssl rand -hex 32`
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
    networks:
      - proxy_proxy-net

  langfuse-db:
    image: postgres
    container_name: langfuse-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=${LANGFUSE_DB_USER}
      - POSTGRES_PASSWORD=${LANGFUSE_DB_PASSWORD}
      - POSTGRES_DB=${LANGFUSE_DB_NAME}
    volumes:
      - ${VOLUMES_BASEDIR}/langfuse/db:/var/lib/postgresql/data
    networks:
      - proxy_proxy-net

networks:
  proxy_proxy-net:
    external: true
