name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/qbittorrent/config:/config
      - ${VOLUMES_ASSETS}/Downloads/torrents:/downloads
    ports:
      - 8080:8080
      - 62609:62609
    networks:
      - proxy_proxy-net
  
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      # - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${VOLUMES_BASEDIR}/deluge/config:/config
      - ${VOLUMES_ASSETS}/Downloads/torrents:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    networks:
      - proxy_proxy-net

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/prowlarr/config:/config
    networks:
      - proxy_proxy-net

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_ASSETS}/Videos/radarr/movies:/movies
      - ${VOLUMES_ASSETS}/Videos/sonarr:/tv
      - ${VOLUMES_BASEDIR}/bazarr/appdata/config:/config
    networks:
      - proxy_proxy-net

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/radarr/appdata/config:/config
      - ${VOLUMES_ASSETS}/Downloads/torrents:/downloads
      - ${VOLUMES_ASSETS}/Videos/radarr/movies:/movies
      - ${VOLUMES_ASSETS}/Videos/radarr/anime:/anime
    networks:
      - proxy_proxy-net

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/sonarr/appdata/config:/config
      - ${VOLUMES_ASSETS}/Videos/sonarr/tv:/tv
      - ${VOLUMES_ASSETS}/Downloads/torrents:/downloads
    networks:
      - proxy_proxy-net

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - "110"
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/jellyfin/config:/config
      - ${VOLUMES_ASSETS}/Videos:/data
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - proxy_proxy-net

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    group_add:
      - "110"
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${VOLUMES_BASEDIR}/plex/config:/config
      - ${VOLUMES_ASSETS}/Videos/radarr/movies:/media/movies
      - ${VOLUMES_ASSETS}/Videos/radarr/anime:/media/anime
      - ${VOLUMES_ASSETS}/Videos/sonarr/tv:/media/tv
    devices:
      - /dev/dri:/dev/dri
    network_mode: host

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_BASEDIR}/jellyseerr/config:/app/config
    networks:
      - proxy_proxy-net

networks:
  proxy_proxy-net:
    external: true