name: 'net'

services:
  cloudflared:
    image: visibilityspots/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - UPSTREAM1=https://1.1.1.1/dns-query
      - UPSTREAM2=https://1.0.0.1/dns-query
      - PORT=5054
      - ADDRESS=0.0.0.0
      - METRICS=127.0.0.1:8088
    networks:
      - proxy_proxy-net

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - cloudflared
    environment:
      - DNSMASQ_USER=pihole
      - WEBPASSWORD=${PIHOLE_PASSWD}
      - TZ=${TIMEZONE}
      - PIHOLE_DNS_=cloudflared#5054
      - WEB_PORT=8053
    volumes:
      - ${VOLUMES_BASEDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${VOLUMES_BASEDIR}/pihole/pihole:/etc/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    networks:
      - proxy_proxy-net
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

networks:
  proxy_proxy-net:
    external: true
  cloudflared-net:
    driver: bridge
