name: 'proxy'

services:
  nginx-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-manager
    restart: unless-stopped
    ports:
    # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ${VOLUMES_BASEDIR}/nginx-manager/data:/data
      - ${VOLUMES_BASEDIR}/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
