name: 'utils'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - ${VOLUMES_BASEDIR}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - '9000:9000'
    networks:
      - proxy_proxy-net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID} # optional, your user id
      - PGID=${PGID} # optional, your group id
    # ports:
    #   - 3000:3000
    volumes:
      - ${VOLUMES_BASEDIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    networks:
      - proxy_proxy-net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_RAW
      - SETUID

networks:
  proxy_proxy-net:
    external: true
